---
- name: INstalling Nginx
  hosts: web-server
  become: true
  
  tasks:
    - name: Installing Nginx
      yum:
      name: nginx 
      state: present

    - name: Starting Nginx
      service:
      name: nginx 
      state: started
  