---
- name: Installing Nginx
  hosts: web-server
  become: true
  
  tasks:
    - name: Install Nginx
      yum:
       name: nginx 
       state: present

    - name: Starting Nginx
      service:
       name: nginx 
       state: started
  